name: Brivele
markdown: kramdown
highligther: pygments
timezone: <timezone>
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: brivele.com
author: Hannah
gems:
    - jekyll-feed
sass:
  style: compressed
